### ISSUE TITLE
black flickering 

### ISSUE THREAD

**Issue by samnotgeorge** [jrodrigv/PhysicsRangeExtender#7]
hello. at high speeds or moderate g forces the parts seem to jitter through each other and create black lines.  i can stop the flickering by turning of the range extender. 

here is a screen shot 
https://steamcommunity.com/id/drivefasteatass/screenshots/

i am sure you will need more info but i dont know what you need

you can reach me at sam10george@gmail.com

**Comment by jrodrigv** [comment]
Hi,

The flickering is due to Unity float physics limit and after KSP 1.4.2 it
became more evident for landed vessels.

Usually the flickering starts to be noticiable when two landed vessels are
at a distance  > 10 km. Even without PRE you will notice the flickering.

However, if both vessels are flying then there is no flickering regardless
of the distance. You can have two planes flying even at 200 km far from
each other without flickering.

I don't think I will be able to fix this because as I said, you can notice
the flickering even on a stock KSP.



El 14 may. 2018 1:50, "samnotgeorge" <notifications@github.com> escribió:

hello. at high speeds or moderate g forces the parts seem to jitter through
each other and create black lines. i can stop the flickering by turning of
the range extender.

here is a screen shot
https://steamcommunity.com/id/drivefasteatass/screenshots/

i am sure you will need more info but i dont know what you need

you can reach me at sam10george@gmail.com

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jrodrigv/PhysicsRangeExtender/issues/7>, or mute the
thread
